<form action="<?= $router->pathFor('radio-action', ['action' => 'lend']) ?>" method="POST">
	<input type="text" 
		   name="borrower"
		   placeholder="<?php echo(empty($r['last-borrower']) ? 'zadej vypůjčitele' : $r['last-borrower']) ?>"
		   autofocus
		   <?php echo(empty($r['last-borrower']) ? 'required' : '') ?>
	>
	<input type="hidden" name="id" value="<?= $r['id'] ?>">
	<input type="hidden" name="radioId" value="<?= $r['radioId'] ?>">
	<input type="hidden" name="last-borrower" value="<?= $r['last-borrower'] ?>">
	<input type="submit" class="pure-button" value="Vypůjčit">
</form>
