<div class="menu pure-menu pure-menu-horizontal">
	<ul class="pure-menu-list">
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('radio-list'); ?>" class="pure-menu-link">Seznam</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('management-radio'); ?>" class="pure-menu-link">Management</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('log'); ?>" class="pure-menu-link">Log</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('qr-generate'); ?>" class="pure-menu-link">Generuj QR</a>
		</li>
	</ul>
</div>
