<div class="menu pure-menu pure-menu-horizontal">

	<ul class="pure-menu-list">
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('radio-list'); ?>" class="pure-menu-link">Seznam radií</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('new-radio'); ?>" class="pure-menu-link">Přidat nové radio</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('log'); ?>" class="pure-menu-link">Log</a>
		</li>
	</ul>

</div>