<div class="menu pure-menu pure-menu-horizontal">
	<ul class="pure-menu-list app-menu-list">
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('radio-list'); ?>" class="pure-menu-link">Seznam</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('management-radio'); ?>" class="pure-menu-link">Management</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('log'); ?>" class="pure-menu-link">Log</a>
		</li>
		<li class="pure-menu-item">
			<a href="<?= $router->pathFor('qr-generate'); ?>" class="pure-menu-link">Generuj QR</a>
		</li>
		<li class="pure-menu-item">
			<a href="/dbadmin" class="pure-menu-link">DB Admin</a>
		</li>
	</ul>
	<label class="signature-widget" for="inputSignature">
		<span>Podpis</span>
		<input type="text" id="inputSignature" placeholder="tvoje jméno" autocomplete="off" autocapitalize="words" spellcheck="false">
	</label>
</div>
<script type="text/javascript" src="/public/signature.js?v=<?= filemtime(__DIR__.'/../public/signature.js') ?>"></script>
