<?php require 'prefix.phtml' ?>

	<h2>RTLS - Přidat nové radio</h2>

<?php require 'main-menu.phtml' ?>

	<article>
		<h4>Přidat rádio: </h4>
		<form method="POST" action="<?= $router->pathFor('add-new-radio'); ?>">
			<input type="text" id="radioId" name="radioId" placeholder="ID rádia" required>
			<input type="text" id="name" name="name" placeholder="Název" required>
			<input type="submit" class="pure-button pure-button-primary" value="Přidat radio">
			
		</form>
		<br/>
		<h4>Hromadný import: </h4>
		<form method="POST" action="<?= $router->pathFor('import-radio'); ?>">
			<textarea name="importRadio" rows="15" cols="60">AA1;Baofeng
AA2;Baofeng</textarea><br/>
			<br/>
			<input type="submit" value="Importovat" class="pure-button">
		</form>
	</article>

<?php require 'suffix.phtml' ?>
