<?php require 'prefix.phtml' ?>

	<h2>RTLS - Seznam rádií</h2>

<?php require 'mainMenu.phtml' ?>

	<article>
		<br/>
		<table class="table pure-table pure-table-striped">
			<thead>
			<tr>
				<th>Radio ID</th>
				<th>Název</th>
				<th>Stav</th>
				<th>Čas poslední akce</th>
				<th>Poslední vypůjčitel</th>
				<th>Akce</th>
			</tr>
			</thead>

			<tbody>
			<?php foreach ($radios as $r): ?>
				<tr>
					<td><?= $r['radioId'] ?></td>
					<td><?= $r['name'] ?></td>
					<td><?= $statusDictionary[$r['status']] ?></td>
					<td><?= $r['last-action-time'] ?></td>
					<td><?= $r['last-borrower'] ?></td>
					<td>
						<?php require ($r['formTemplateLink']); ?>
					</td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
	</article>

<?php require 'suffix.phtml' ?>