<?php require 'prefix.phtml' ?>

	<h2>RTLS - Seznam rádií</h2>

<?php require 'mainMenu.phtml' ?>

	<article>
		<br/>
		<table class="table pure-table pure-table-striped">
			<thead>
			<tr>
				<th>Radio ID</th>
				<th>Název</th>
				<th>Stav</th>
				<th>Čas poslední výpůjčky</th>
				<th>Poslední vypůjčitel</th>
				<th>Akce</th>
			</tr>
			</thead>

			<tbody>
			<?php foreach ($radios as $r): ?>
				<tr>
					<td><?= $r['radioId'] ?></td>
					<td><?= $r['name'] ?></td>
					<td><?= $r['status'] ?></td>
					<td><?= $r['last-returned-time'] ?></td>
					<td><?= $r['last-borrower'] ?></td>
					<td>
						<form action="<?= $r['link'] ?>" method="POST">
							<input type="hidden" name="id" value="<?= $r['id'] ?>">
							<input type="hidden" name="radioId" value="<?= $r['radioId'] ?>">
							<input type="submit" class="pure-button" value="<?= $r['linkLabel'] ?>">
						</form>
					</td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
	</article>

<?php require 'suffix.phtml' ?>